package mongorepo

import (
	"time"

	"go.mongodb.org/mongo-driver/bson/primitive"

	"recipes-desk/internal/modules/auth/domain"
)

// refreshTokenModel represents a refresh token in MongoDB.
type refreshTokenModel struct {
	ID        primitive.ObjectID `bson:"_id,omitempty"` //nolint:tagliatelle // MongoDB _id field
	UserID    primitive.ObjectID `bson:"userId"`
	TokenHash string             `bson:"tokenHash"`
	ExpiresAt time.Time          `bson:"expiresAt"`
	CreatedAt time.Time          `bson:"createdAt"`
}

// SetTimestamps sets the creation and expiration timestamps.
func (m *refreshTokenModel) setTimestamps(expiry time.Duration) {
	now := time.Now()
	if m.CreatedAt.IsZero() {
		m.CreatedAt = now
	}
	m.ExpiresAt = now.Add(expiry)
}

func (m *refreshTokenModel) setID() {
	m.ID = primitive.NewObjectID()
}

func (m *refreshTokenModel) prepareForInsert(expiry time.Duration) {
	m.setTimestamps(expiry)
	m.setID()
}

// toDomain converts a MongoDB refresh token model to a domain refresh token.
func (m *refreshTokenModel) toDomain() *domain.RefreshToken {
	return &domain.RefreshToken{
		ID:        m.ID.Hex(),
		UserID:    m.UserID.Hex(),
		TokenHash: m.TokenHash,
		ExpiresAt: m.ExpiresAt,
		CreatedAt: m.CreatedAt,
	}
}

// refreshTokenModelFromDomain converts a domain refresh token to a MongoDB model.
func refreshTokenModelFromDomain(token *domain.RefreshToken) (*refreshTokenModel, error) {
	userID, err := primitive.ObjectIDFromHex(token.UserID)
	if err != nil {
		return nil, err
	}

	return &refreshTokenModel{
		ID:        primitive.NilObjectID, // will be generated by MongoDB
		UserID:    userID,
		TokenHash: token.TokenHash,
		ExpiresAt: token.ExpiresAt,
		CreatedAt: token.CreatedAt,
	}, nil
}
